# Generated by Django 5.2.7 on 2025-11-13 15:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название товара",
                        max_length=50,
                        verbose_name="Название",
                    ),
                ),
                (
                    "model_product",
                    models.CharField(
                        blank=True,
                        help_text="Введите модель",
                        max_length=200,
                        null=True,
                        verbose_name="Модель",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Введите дату выхода продукта на рынок",
                        verbose_name="Дата выхода",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название фирмы",
                        max_length=100,
                        verbose_name="Название фирмы",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Введите страну",
                        max_length=100,
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Введите город",
                        max_length=100,
                        null=True,
                        verbose_name="Город",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Введите адрес (улица, № дома)",
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("factory", "завод"),
                            ("retail", "розничная сеть"),
                            ("entrepreneur", "индивидуальный предприниматель"),
                        ],
                        default="factory",
                        max_length=35,
                        verbose_name="Тип юридического лица",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Определяется автоматически",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Уровень в иерархии",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите поставщика-источник. Если отсутствует — оставьте пустым.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="suppliers.supplier",
                        verbose_name="Поставщик (предыдущий уровень)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
            },
        ),
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Размер задолженности перед поставщиком",
                        max_digits=10,
                        verbose_name="Задолженность",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suppliers.product",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemes",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь звеньев",
                "verbose_name_plural": "Связи звеньев",
            },
        ),
    ]
